### ISSUE TITLE
new icon

### ISSUE THREAD

**Issue by zeke** [electron/trop#26]
How about a new icon that is more evocative of what Trop is doing?

A few quick ideas:

<img width="308" alt="screen shot 2018-03-19 at 5 06 26 pm" src="https://user-images.githubusercontent.com/2289/37679460-3dd08360-2c3e-11e8-9e32-d7473a9298bd.png">

<img width="317" alt="screen shot 2018-03-19 at 5 11 46 pm" src="https://user-images.githubusercontent.com/2289/37679464-3f8c9900-2c3e-11e8-9d8b-2a078d9378d5.png">

**Comment by ckerr** [comment]
![current icon](https://avatars0.githubusercontent.com/u/37298512?s=400&v=4) 

You're right that the current icon doesn't do a good job of visualizing what trop does; it just says "this is a bot."

I do like the current icon's sense of fun, especially since trop eliminates a non-fun task. IMO it would be great if a replacement icon was more descriptive _and_ maintained that playfulness.

**Comment by zeke** [comment]
<img width="352" alt="screen shot 2018-03-20 at 3 40 25 pm" src="https://user-images.githubusercontent.com/2289/37686509-094d1736-2c55-11e8-875a-801df8778b2f.png">

**Comment by ckerr** [comment]
So simple. Inspired!

**Comment by codebytere** [comment]
oh im fond of that last one too...can we change it to electron-ish colors maybe? then 💯

**Comment by zeke** [comment]
![image](https://user-images.githubusercontent.com/2289/37856492-e3d8f25e-2eb1-11e8-8931-7027e475f308.png)

**Comment by zeke** [comment]
I see the new icon in the wild! Opened #33 which adds the icon files to this repo.

![image](https://user-images.githubusercontent.com/2289/38050224-2517465a-327f-11e8-9392-50f5cdb2b189.png)
